services:
  - type: web
    name: tilus-tech
    env: node
    # Optionnel : si vous voulez une version précise de Node (basé sur vos logs)
    # nodeVersion: 20.04.1
    buildCommand: npm install
    startCommand: node src/server.js # ✅ Correction ici (on ajoute src/)
    plan: free
